DROP TABLE IF EXISTS brands;
DROP TABLE IF EXISTS categories;


CREATE TABLE brands (
	id 			SERIAL NOT NULL PRIMARY KEY,
	name		VARCHAR(255) NOT NULL,
	created_at 	TIMESTAMP WITH TIME ZONE,
	updated_at	TIMESTAMP WITH TIME ZONE
);

CREATE TABLE categories (
	id 			SERIAL NOT NULL PRIMARY KEY,
	brand_id	INT NOT NULL REFERENCES brands (id) ON DELETE CASCADE ON UPDATE CASCADE,
	parent_id	INT NULL REFERENCES categories (id) ON DELETE CASCADE ON UPDATE CASCADE,
	name		VARCHAR(255) NOT NULL,
	url		    TEXT NOT NULL,
	created_at 	TIMESTAMP WITH TIME ZONE,
	updated_at	TIMESTAMP WITH TIME ZONE
);